### ISSUE TITLE
[parallelized-aws-lambda] Issue with headless chrome and Amazon Linux 

### ISSUE THREAD

**Issue by diogeneshamilton** [redotvideo/examples#10]
I'm getting an error (failed to launch browser process) because the latest version of Chrome (127.0.6533.72) needs to use a version of CUPS which doesn't seem to be installed in the latest Amazon Linux environment (which is in the Dockerfile). Specifically it can't find httpConnect2:

`undefined reference to "httpConnect2"`

I have tried to find a solution for a PR, but so far can't seem to find the right package to install in the Docker image. 

For now, I've pinned the versions of puppeteer and @sparticuz/chromium:
```
"@sparticuz/chromium": "126.0.0",
"puppeteer": "22.13.1",
```

**Comment by justusmattern27** [comment]
thanks, it's probably better to pin the versions in general - will update it!

**Comment by itsanishjain** [comment]
Hey did you able to fix this issue, I tried to do rendering using lambda and still getting this same error

```
Lambda invoke result: {
  statusCode: 500,
  body: '{"error":"Error during partial render: Error: Failed to launch the browser process!\\n/var/task/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome: symbol lookup error: /var/task/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome: undefined symbol: httpConnect2\\n\\n\\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\\n"}'
}
```

**Comment by justusmattern27** [comment]
@itsanishjain hey, you should be able to fix this by using the chrome binary from the `@sparticuz/chromium` package through the `executablePath` option in `renderPartialVideo`:

```
puppeteer: { 
args: chromium.args, headless: chromium.headless,
executablePath: await chromium.executablePath(),
 }

```

**Comment by itsanishjain** [comment]
> @itsanishjain hey, you should be able to fix this by using the chrome binary from the `@sparticuz/chromium` package through the `executablePath` option in `renderPartialVideo`:
> 
> ```
> puppeteer: { 
> args: chromium.args, headless: chromium.headless,
> executablePath: await chromium.executablePath(),
>  }
> ```

Worked for me
P.S. don't forget to rebuild your project

**Comment by diogeneshamilton** [comment]
Yep, I will close this since the example seems to fix at this point.
